# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class OneEnvCli < Formula
  desc ""
  homepage "https://github.com/ericflores108"
  version "0.4"

  on_macos do
    url "https://github.com/ericflores108/one-env-cli/releases/download/v0.4/one-env-cli_Darwin_all.tar.gz"
    sha256 "52d1e6d246bd1dea22d00a446553ec8bdc75106be6814bc7da00c74f2fade86e"

    def install
      bin.install "one-env-cli"
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      url "https://github.com/ericflores108/one-env-cli/releases/download/v0.4/one-env-cli_Linux_x86_64.tar.gz"
      sha256 "84606b0f108e332b67ecf852b4f45b32de02d42eb782775eee4b2b2849236b7b"

      def install
        bin.install "one-env-cli"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/ericflores108/one-env-cli/releases/download/v0.4/one-env-cli_Linux_arm64.tar.gz"
      sha256 "b8213210b30435ebb21d2c06a01a2ded4302ea4c2f3f623219ffa374d7753f4a"

      def install
        bin.install "one-env-cli"
      end
    end
  end
end
